<?php

namespace AppBundle\Repository;

/**
 * DydaktykaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DydaktykaRepository extends \Doctrine\ORM\EntityRepository
{
}
