<?php

namespace AppBundle\Repository;

/**
 * StronaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StronaRepository extends \Doctrine\ORM\EntityRepository
{
}
