imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

    templating:
            engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes: ['bootstrap_4_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


# Dodane przeze mnie

# knp_paginator  configuration
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template


# FOS user bundle configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\Autor
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

    registration:
        form:
            type: AppBundle\Form\RegistrationFormType


# EasyAdminBundle
easy_admin:
    site_name: 'Panel administracyjny'
    search:
        title: 'Wyniki wyszukiwania'
    design:
        brand_color: '#8c231b'
        menu:
            - { entity: 'Pracownicy', icon: 'users' }
            - { entity: 'Uzytkownicy', icon: 'address-book' }
            - { entity: 'Dydaktyka', icon: 'graduation-cap' }
    formats:
        datetime: 'd-m-Y H:i:s'
    list:
        #label: 'Akcje'
        actions:
            - { name: 'edit', icon: 'pencil', label: 'Edytuj' }
            - { name: 'show', icon: 'eye', label: 'Pokaż' }
            - { name: 'delete', icon: 'trash', label: 'Usuń' }
            - { name: 'search', label: 'Szukaj' }
            - { name: 'new', icon: 'plus-circle',label: 'Nowy' }
    entities:
        Pracownicy:
            class: AppBundle\Entity\Strona
            form:
                fields: ['tytul', 'tresc', 'autor']
            label: 'Pracownicy'
            list:
                title: "Pracownicy wydziału"
                fields: ['id', 'tytul', 'dataStworzenia', 'autor']
            search:
                fields: ['tytul', 'tresc', 'autor']
            edit:
                title: 'Edytuj pracownika'
                actions:
                    - { name: 'delete', label: 'Usuń' }
            show:
                title: 'Podgląd pracownika'
                actions:
                    - { name: 'edit', label: 'Edytuj' }
                    - { name: 'delete', label: 'Usuń' }
        Uzytkownicy:
            class: AppBundle\Entity\Autor
            form:
                fields: [{property: 'imie', label: 'Imię'}, 'nazwisko', {property: 'username', label: 'Nazwa użytkownika'},'email', {property: 'password', label: 'Hasło'}, {property: 'roles', label: 'Uprawnienia'}, {property: 'strona', label: 'Dodani pracownicy'}]
            label: 'Użytkownicy'
            list:
                title: "Zarejestrowani użytkownicy"
                fields: ['id', {property: 'imie', label: 'Imię'}, 'nazwisko', 'email', {property: 'username', label: 'Nazwa użytkownika'}, {property: 'enabled', label: 'Aktywny'}, {property: 'lastLogin', label: 'Ostatnie logowanie'}]
            search:
                fields: ['imie', 'nazwisko', 'email', 'username']
            edit:
                title: 'Edytuj użytkownika'
                actions:
                    - { name: 'delete', label: 'Usuń' }
            show:
                title: 'Podgląd użytkownika'
                fields: ['id', {property: 'imie', label: 'Imię'}, 'nazwisko', {property: 'username', label: 'Nazwa użytkownika'},'email', {property: 'password', label: 'Hasło'}, {property: 'roles', label: 'Uprawnienia'}, {property: 'enabled', label: 'Aktywny'}, {property: 'lastLogin', label: 'Ostatnie logowawnie'}, {property: 'strona', label: 'Dodani pracownicy'}]
                actions:
                    - { name: 'edit', label: 'Edytuj' }
                    - { name: 'delete', label: 'Usuń' }
        Dydaktyka:
                    class: AppBundle\Entity\Dydaktyka
                    form:
                        fields: ['tresc', 'autor']
                    label: 'Dydaktyka'
                    list:
                        title: "Dydaktyka"
                        fields: ['id', 'tytul', 'tresc', 'autor']
                    search:
                        fields: ['tytul', 'tresc', 'autor']
                    edit:
                        title: 'Edytuj'
                        actions:
                            - { name: 'delete', label: 'Usuń' }
                    show:
                        title: 'Podgląd'
                        actions:
                            - { name: 'edit', label: 'Edytuj' }
                            - { name: 'delete', label: 'Usuń' }